### ISSUE TITLE
How do I login?

### ISSUE THREAD

**Issue by pjrezai** [deepwather/plexDash#1]
It says to login over browser but how? what is the port?

**Comment by thenamelessthing** [comment]
Indeed, how do we login? I mean which url we havte to use?

**Comment by itsecbern** [comment]
Hello Guys, as apparent form the "Example Installation" on the project-page there is by default no standard Port. This Project is only a CMS. You need to install an Apache or Nginx webserver with PhP 5.6. and mcrypt enabled. The default port is then :80 reachable over your PlexserverIP:80 -> e.g. (http://192.168.1.23)

Cheers deepwather
